version: '3.8'
services:
  postgresdb:
    image: postgres
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - '$DB_PORT:5432'  
    volumes:
      - ./database/localdb:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d  