version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "${BACKEND_EXPOSED_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgresdb
    restart: always
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/app.js:/usr/src/app/app.js

  postgresdb:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - '${POSTGRES_EXPOSED_PORT}:5432'  
    volumes:
      - ./backend/database/localdb:/var/lib/postgresql/data
      - ./backend/database/scripts:/docker-entrypoint-initdb.d  